---
  - name: Ensure previous docker is removed
    command: yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine -y
    register: res
    failed_when: res.rc != 0

  - name: Ensure ports are free before installing controller.
    command: "{{ item }}"
    register: res
    failed_when: false
    with_items:
    - "pkill -9 epmd"
    - "pkill -9 httpd"
    - "pkill -9 haproxy"
    - "pkill -9 beam.smp"
    - "systemctl stop openvswitch"
    - "rpm -e openvswitch"