---
  - name: Add epic workers into cluster and install bundle.
    hosts: localhost
    gather_facts: false
    roles:
      - role: epic-worker
        vars:
          addworkers: yes

  - name: Delete epic workers from cluster.
    hosts: localhost
    gather_facts: false
    roles:
      - role: epic-worker
        vars:
          deleteworkers: yes
          delete_pools:
            - worker: 10.1.10.21
